/**
 * Bilibili Cookie 工具函数
 */

/**
 * 获取 Bilibili cookies 并转换为 Netscape 格式（yt-dlp 兼容格式）
 * @returns {Promise<string|null>} 返回 cookies 文件内容或 null
 */
async function getBilibiliCookiesForYtDlp() {
  try {
    // 检查是否具有 cookies 权限
    if (!chrome.cookies) {
      console.warn('[VisionMark] 浏览器不支持 cookies API');
      return null;
    }

    // 获取所有 bilibili.com 域名的 cookies
    const cookies = await chrome.cookies.getAll({
      domain: '.bilibili.com'
    });

    if (cookies.length === 0) {
      console.warn('[VisionMark] 未找到 Bilibili cookies，请确保已登录 Bilibili');
      return null;
    }

    const requiredCookieNames = ['SESSDATA', 'bili_jct', 'DedeUserID'];
    const existingCookieNames = new Set(cookies.map(cookie => cookie.name));
    const missingRequiredCookies = requiredCookieNames.filter(name => !existingCookieNames.has(name));
    if (missingRequiredCookies.length > 0) {
      console.warn(`[VisionMark] 检测到关键登录 cookies 缺失: ${missingRequiredCookies.join(', ')}`);
    }

    // 转换为 Netscape cookies.txt 格式
    // 格式: domain\tflag\tpath\tsecure\texpiration\tname\tvalue
    const cookieLines = cookies.map(cookie => {
      const rawDomain = cookie.domain || '.bilibili.com';
      const isHostOnly = Boolean(cookie.hostOnly);
      const domain = isHostOnly
        ? rawDomain.replace(/^\./, '')
        : (rawDomain.startsWith('.') ? rawDomain : `.${rawDomain}`);
      const flag = isHostOnly ? 'FALSE' : 'TRUE';
      const path = cookie.path || '/';
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      const expiration = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
      const name = cookie.name;
      const value = cookie.value;

      return [domain, flag, path, secure, expiration, name, value].join('\t');
    });

    // 添加文件头注释
    const header = `# Netscape HTTP Cookie File
# This file was automatically generated by VisionMark extension
# https://www.bilibili.com cookies for yt-dlp
`;
    
    return header + cookieLines.join('\n') + '\n';
  } catch (error) {
    console.error('[VisionMark] 获取 Bilibili cookies 失败:', error);
    return null;
  }
}

/**
 * 检查用户是否已登录 Bilibili
 * @returns {Promise<boolean>}
 */
async function isUserLoggedInToBilibili() {
  try {
    if (!chrome.cookies) {
      return false;
    }
    
    const cookies = await chrome.cookies.getAll({
      domain: '.bilibili.com',
      name: 'SESSDATA'
    });
    
    return cookies.length > 0;
  } catch (error) {
    console.error('[VisionMark] 检查 Bilibili 登录状态失败:', error);
    return false;
  }
}

// 导出函数
window.VisionMarkCookieUtils = {
  getBilibiliCookiesForYtDlp,
  isUserLoggedInToBilibili
};